### ISSUE TITLE
Comics at some point?

### ISSUE THREAD

**Issue by strcmp** [RubyWebComicsSociety/RubyWebComicsSociety.github.io#1]
Hi.
Just curious if the repository and site will be updated to have some ruby-centered comics at some point, or is this site to promote the ruby library for building comics?

**Comment by Mav7** [comment]
@strcmp Yeah, it's going to be the site for promoting our library for building a webcomics site; like http://mangastream.com/ for instance. Here's a link to an example app we created with the library http://canvascomics.herokuapp.com/.

**Comment by Mav7** [comment]
@strcmp Off topic, I was going to ask you if maybe you'd like to help me document mruby's C API. I really appreciate your help on there and we could probably cover more ground together!

**Comment by strcmp** [comment]
I see, that's still very cool. :)
